export const FETCH_CLIENT_REQUEST = 'FETCH_CLIENT_REQUEST';
export const FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS';
export const FETCH_CLIENT_ERROR = 'FETCH_CLIENT_ERROR';
export const FETCH_CLIENTINFO_REQUEST = 'FETCH_CLIENTINFO_REQUEST';
export const FETCH_CLIENTINFO_SUCCESS = 'FETCH_CLIENTINFO_SUCCESS';
export const FETCH_CLIENTINFO_ERROR = 'FETCH_CLIENTINFO_ERROR';