export const FETCH_CREATE_MAP_TRACKING_REQUEST = 'FETCH_CREATE_MAP_TRACKING_REQUEST';
export const FETCH_CREATE_MAP_TRACKING_SUCCESS = 'FETCH_CREATE_MAP_TRACKING_SUCCESS';
export const FETCH_CREATE_MAP_TRACKING_ERROR = 'FETCH_CREATE_MAP_TRACKING_ERROR';