export const FETCH_SCHEDULE_REQUEST = 'FETCH_SCHEDULE_REQUEST';
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';
export const FETCH_SCHEDULE_ERROR = 'FETCH_SCHEDULE_ERROR';
export const FETCH_ADDSCHEDULE_REQUEST = 'FETCH_ADDSCHEDULE_REQUEST';
export const FETCH_ADDSCHEDULE_SUCCESS = 'FETCH_ADDSCHEDULE_SUCCESS';
export const FETCH_ADDSCHEDULE_ERROR = 'FETCH_ADDSCHEDULE_ERROR';